/**
    @author kenneth.cruz@unah.hn
    @version 0.0.1
    @date 11/3/2021 
*/

--
-- DEPARTAMENTO
--

SELECT 
    ID_DEPARTAMENTO AS id_departamento,
    DEPARTAMENTO AS nombre
FROM 
    DEPARTAMENTO
;


--
-- CLIENTE
--

SELECT 
    ID_CLIENTE AS id_cliente, 
    CONCAT(NOMBRE, ' ', APELLIDO) AS nombre
FROM
    CLIENTE
;


--
-- EMPLEADO
--

SELECT 
    ID_EMPLEADO AS id_empleado, 
    CONCAT(NOMBRE, ' ', APELLIDO) AS nombre
FROM
    EMPLEADO
;


--
-- TIEMPO
--

SELECT 
    PAGO.ID_PAGO AS id_tiempo, 
    CONVERT(DATE, FECHA_PAGO) AS fecha,
    DATEPART(YEAR, FECHA_PAGO) AS año, 
    DATEPART(MONTH, FECHA_PAGO) AS mes, 
    DATEPART(WEEK, FECHA_PAGO) AS semana, 
    DATEPART(QUARTER, FECHA_PAGO) AS trimestre, 
    CASE 
        WHEN MONTH(DATEPART(MONTH, FECHA_PAGO)) < 7  THEN 1 ELSE 2 
    END AS semestre, 
    DATENAME(WEEKDAY, FECHA_PAGO) AS dia_semana 
FROM 
    PAGO 
;


--
-- HECHOS_PAGO
--

SELECT
    PAGO.ID_PAGO AS id_pago, 
    DEPARTAMENTO.ID_DEPARTAMENTO AS id_departamento, 
    CLIENTE.ID_CLIENTE AS id_cliente, 
    EMPLEADO.ID_EMPLEADO AS id_empleado, 
    PAGO.ID_PAGO AS id_tiempo, 
    PAGO.MONTO AS monto
FROM 
    PAGO
INNER JOIN 
    EMPLEADO ON EMPLEADO.ID_EMPLEADO = PAGO.ID_EMPLEADO
INNER JOIN
    CLIENTE ON CLIENTE.ID_CLIENTE = PAGO.ID_CLIENTE
INNER JOIN
    DIRECCION ON DIRECCION.ID_DIRECCION = CLIENTE.ID_DIRECCION
INNER JOIN
    CIUDAD ON CIUDAD.ID_CIUDAD = DIRECCION.ID_CIUDAD
INNER JOIN
    DEPARTAMENTO ON DEPARTAMENTO.ID_DEPARTAMENTO = CIUDAD.ID_DEPARTAMENTO
;